name: photomarc
favicon: null
layout_spectrum: 0.49729
typography_spectrum: 0.93618
title: "Marc's Photos"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6c7684'
    - '#9f9f9f'
    - '#c6c2b8'
    - '#323b42'
  brandStrength: 0
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0
purpose: []
