name: photomarc
favicon: null
layout_spectrum: 0.92279
typography_spectrum: 0.43194
title: "Marc's Photos"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3a3221'
    - '#52452f'
    - '#746347'
    - '#897351'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
