name: photomarc
favicon: null
layout_spectrum: 0.06903343368321657
typography_spectrum: 0.5523501462303102
title: "Marc's Photos"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8850629886146635
  lightness: 0.7739126875530928
  saturation: 0.9137552094180137
  rhythmicContrast: 0.024541320744901896
purpose: []
