name: photomarc
favicon: null
layout_spectrum: 0.16662
typography_spectrum: 0.43194
title: "Marc's Photos"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6eef8'
    - '#a2bcd3'
    - '#50392c'
    - '#5b7591'
    - '#000000'
  brandStrength: 0
  lightness: 0.7739126875530928
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
