name: photomarc
favicon: null
layout_spectrum: 0.37734
typography_spectrum: 0.13332
title: "Marc's Photos"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3a3221'
    - '#52452f'
    - '#746347'
    - '#897351'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0
purpose: []
